### ISSUE TITLE
Improve Stats + add Stats V1

### ISSUE THREAD

**Issue by Luc1412** [Terbau/fortnitepy#11]
Stats V1:
def get_stats(account_id, timewindow)

Endpoint: https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/stats/accountId/{account_id}/bulk/window/{timewindow}
If response.status =! 200 or response.json == {}:
  Account is private

How the stats Dict look like:
platform_stats_entry = stats[Platform.PLATFORM(eg. PC)]

class PlatformStatsEntry
stats_entry = platform_stats_entry.solo (p2)
platform_stats_entry.duo (p10)
platform_stats_entry.squad (p9)
platform_stats_entry.all (p2 + p9 +p10)

class StatsEntry
stats_entry.wins (placetop1)
stats_entry.top3 (placetop3)
stats_entry.top5 (placetop5)
stats_entry.top6 (placetop6)
stats_entry.top10 (placetop10)
stats_entry.top12 (placetop12)
stats_entry.top25 (placetop25)
stats_entry.matches_played (matchesplayed)
stats_entry.kills (kills)
stats_entry.score (score)
stats_entry.minutes_played (minutesplayed)
stats_entry.last_modified (lastmodified)
stats_entry.top3 (placetop3)
stats_entry.kills_per_game (kills / matches)
stats_entry.score_per_gam3 (score / matches)
stats_entry.win_ratio (wins / matches * 100)
stats_entry.deaths (games - wins)
stats_entry.kd (kills / deaths)

Platform Enum:
PC = 'pc'
XBOX = 'xb1'
PLAYSTATION = 'ps4'

StatsV2 improvements:
- Add Predefined Start/End Time -> Seasonal Stats
If response.status =! 200 or response.json == {}:
  Account is private

input_stats_entry = stats[Input.INPUT_TYPE(eg. TOUCH)]

class InputStatsEntry:
input_stats_entry.solo (defaultsolo)
input_stats_entry.duo (defaultsquad)
input_stats_entry.squad (defaultsquad)
input_stats_entry.ltm[{ltm_name}
input_stats_entry.solo_all (defaultsolo + all ltm .startswith(solo) + Carmine ltm)
input_stats_entry.duo_all (defaultsolo + all ltm .startswith(solo))
input_stats_entry.squad_all  (defaultsolo + all ltm .startswith(solo))

input_stats_entry.all
input_stats_entry.all_all

classStatsEntry:
similar to V1 only some placetop are missing

Platform InputType:
KEYBOARDMOUSE = 'keyboardmouse'
CONTROLLER = 'gamepad'
TOUCH = 'touch'

**Comment by Terbau** [comment]
I'm planning on adding StatsV1 support to the library soon and some of your points seems like a good fit for the library. I'm pushing an update before I go on vacation (saturday) but V1 support will sadly not be apart of this update since it's not high priority.

**Comment by iXyles** [comment]
I guess you can close this issue now due to the fact that Epic has deprecated V1 and closed it down.
