### ISSUE TITLE
Add Fish end

### ISSUE THREAD

**Issue by Luc1412** [Terbau/fortnitepy#124]
With the start of S4, Epic added a new endpoint to get the fish stats:
 POST https://statsproxy-public-service-live.ol.epicgames.com/statsproxy/api/statsv2/query?category=collection_fish

Payload: 
{
    "appId": "fortnite",
    "startDate": 0,
    "endDate": 9223372036854775807,
    "owners": [
        "6e4295fa931e44958e6eff17261464fc"
    ]
}

It should be easy to implement and might be useful for some ppl.

**Comment by Terbau** [comment]
Thanks for the suggestion. I added some methods for fetching collections in version 3.2.0 which was just released :)
