### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Milimarty** [Terbau/fortnitepy#127]
can you create a tutorial for the login section?  I don't know what is auth_device.json file is? and how can I get device_id and secret?
I try to create a bot for tracking Fortnite player's stats but I cant to login with email and password.
and I can't find it in the documentation .
Thank you for your help !!

**Comment by edsonpez** [comment]
x2, please, I am having this problem too

**Comment by XtremeFN** [comment]
when you go to the examples then whatever one you want you put in the account info such as password and email then open tis link to get the code to run the bot, its basic stuff but for people that didn't know ill link to the link only copy the numbers not the whole thing the numbers    https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode

**Comment by XtremeFN** [comment]
@Milimarty
