### ISSUE TITLE
Add Support for Support a Creator Checks

### ISSUE THREAD

**Issue by Luc1412** [Terbau/fortnitepy#13]
Endpoint to check if a Code is valid:
GET `https://affiliate-public-service-prod.ol.epicgames.com/affiliate/api/public/affiliates/slug/%creator_code%`

Search for a Creator Code:
GET unknown

For more information about the Endpoints/the usage you can maybe ask amrsatrio#8564. He has advanced knowledge.

**Comment by xMistt** [comment]
+1

**Comment by Terbau** [comment]
This has finally been implemented in with Client.search_sac_by_slug() in fortnitepy v2.0.0.
