### ISSUE TITLE
Prevent duplicate account ids in run_multiple

### ISSUE THREAD

**Issue by demipixel** [Terbau/fortnitepy#140]
I'm sure not a priority at all, but I accidentally was generating device auths for one account for what I thought was multiple accounts. Fornitepy didn't complain at all and just ran them, which caused... interesting issues, which were not super helpful in the debugging the issue (mostly "unknown party id" bugs).

I absolutely would not *expect* Fortnitepy to have known any better, but a simple check on `fortnitepy.run_multiple()` to ensure that no accounts have the same `account_id` could be potentially helpful in preventing this issue for any future devs.

**Comment by Terbau** [comment]
Seems like a good idea. I'll make sure its added in the next update :)
