### ISSUE TITLE
Move user?

### ISSUE THREAD

**Issue by hackermondev** [Terbau/fortnitepy#143]
Is it possible to move the fortnite user in the game with this library?

**Comment by hackermondev** [comment]
@Terbau

**Comment by Terbau** [comment]
If you are talking about team positions in the lobby then you can use this to swap position between the client and a member https://fortnitepy.readthedocs.io/en/latest/api.html#fortnitepy.PartyMember.swap_position. If you need any more help with swapping two members (not including the client), you can join the support discord and ask for help in #fortnitepy-help.

I'll leave this issue open for now and tag it as an enhancement as swap requests between two members more easily is something I want to support in the future.

**Comment by hackermondev** [comment]
@Terbau no i mean like when the party leader choose a game mode, the bot can ready up and when it joins into the game move around in the game and like get positions of other party members and other stuff.

**Comment by Terbau** [comment]
Bots can't join games and they cannot read party members positions. If you wish to do this you must parse replays. Note that parsing replays can only be done after the game itself is done due to the encryption key not being added until then.
