### ISSUE TITLE
Add changing skins with cid

### ISSUE THREAD

**Issue by lukas819** [Terbau/fortnitepy#16]
Can you make that we can change skins with cid and eid etc. and change the skin not with the name?

**Comment by Terbau** [comment]
This is already a feature :)
https://fortnitepy.readthedocs.io/en/latest/api.html#fortnitepy.PartyMember.set_outfit

**Comment by lukas819** [comment]
Can you help me to change skins with cid im not really a pro in python. when i make the command in my python file then the file wont start.

**Comment by Terbau** [comment]
For support questions I recommend joining [this](https://discordapp.com/invite/rnk869s) discord server dedicated for discussion/support around fortnite related apps and libraries.
