### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by lukas819** [Terbau/fortnitepy#22]
I want that the bot have a skin when i start the bot and join the bot when i make this command in my python file: " async def event_party_member_join(self, member):
        clientmember = client.user.party.me
        await clientmember.set_outfit(asset="CID_467_Athena_Commando_M_WeirdObjectsPolice")" then the file is not starting.

**Comment by Terbau** [comment]
Using this library requires some knowledge of python and coding i general. First of all this issue includes very little information on what the issue really is (no code context, no errors etc.). I would also suggest joining the discord linked in readme for support.
