### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by creator1372** [Terbau/fortnitepy#53]
`AttributeError: 'PartyInvitation' object has no attribute 'author'`
When you try doing something like on_party_invite: `print(f"Accepted party invite from {invite.author.display_name}")` it outputs this error.

**Comment by Terbau** [comment]
`PartyInvitation.author` was recently renamed to `PartyInvitation.sender`. https://fortnitepy.readthedocs.io/en/latest/api.html#fortnitepy.PartyInvitation.sender
