### ISSUE TITLE
Add Support for Fortnite Gamemode List (with active ones)

### ISSUE THREAD

**Issue by Luc1412** [Terbau/fortnitepy#7]
Get all Gamemodes:
Endpoint: https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game
Where is the data stored: `result['playlistinformation']['playlist_info']['playlists']`
What is important? `image`, `name`, `violator`, `description` (Name is internal)

How to get the Real Playlist Names:
Trough the Game files, but I dunno the Location

How to get actives:
Endpoints: https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/calendar/v1/timeline
Where is the data stored: `result['channels']['client-matchmaking']['states'][INDEX]`
Check date/time: `data['validFrom']`
Get the Infos: `data['state']['region'][REGION]['eventFlagsForcedOn'][INDEX]`

**Comment by Terbau** [comment]
Thanks for the request. I have implemented both fetching of all playlists and fetching of currently active LTMs for a specific region.

Unfortunately, as you already know, I have decided to postpone a potential solution for gathering the actual display names of the playlists from the files. This might become an extension at a later time.
