### ISSUE TITLE
Sorry your login does not posses the permissions 'account:public:account:deviceAuths CREATE' needed to perform the requested operation

### ISSUE THREAD

**Issue by frehan** [Terbau/fortnitepy#71]
Trying to call account_generate_device_auth but allways get the following error back:
{
  "errorCode": "errors.com.epicgames.common.missing_permission",
  "errorMessage": "Sorry your login does not posses the permissions 'account:public:account:deviceAuths CREATE' needed to perform the requested operation",
  "messageVars": [
    "account:public:account:deviceAuths",
    "CREATE"
  ],
  "numericErrorCode": 1023,
  "originatingService": "com.epicgames.account.public",
  "intent": "prod"
}

Any idea why?

**Comment by Terbau** [comment]
This method is not meant to be called by you. It's called in AdvancedAuth if no device auth details was passed. You can get the details genereated in AdvancedAuth from event_device_auth_generate().

**Comment by frehan** [comment]
Thanks for the reply but I am trying to create my own version of the Advanced Auth in c# but can not call the method generate_device_auth in a correct way, trying to figure out why 😊
