### ISSUE TITLE
Add a way to get on the last updat date for battle pass level methods.

### ISSUE THREAD

**Issue by Luc1412** [Terbau/fortnitepy#88]
The fetch_battlepass_level and fetch_multiple_battlepass_level should include way to get on the last update date or check the date internal, because you need to check whether the last update was in the latest Season or not. Otherwise the BP lvl from the Season before is shown.
So either the method will check it itself and set the BP in this case to 0 or the method provide this date.

**Comment by Terbau** [comment]
Forgot to close the issue but this feature request was implemented in v2.0.
